/**
 * Wire protocol shared between the Node bridge and the Studio plugin.
 *
 * Transport is deliberately dumb: the server pushes `Command` frames down an
 * SSE stream (or hands them out via long-poll when SSE is unavailable) and the
 * plugin POSTs a matching `CommandResult` back to /result. Every frame is
 * correlated by `id`, so both transports behave identically from the tool side.
 */

/** A single request from the MCP server to one Studio instance. */
export interface Command {
  id: string;
  /** Handler name the plugin dispatches on, e.g. "inspect" or "script.edit". */
  op: string;
  params: Record<string, unknown>;
}

/** Structured failure returned by the plugin. `hint` is surfaced to the agent. */
export interface CommandError {
  code: string;
  message: string;
  hint?: string;
}

export interface CommandResult {
  id: string;
  ok: boolean;
  data?: unknown;
  error?: CommandError;
}

/** Identity a plugin declares when it opens its stream. */
export interface StudioIdentity {
  /** Stable per-Studio-process id generated by the plugin. */
  studioId: string;
  placeName: string;
  placeId: number;
  /** Plugin version, used to warn on protocol drift. */
  pluginVersion: string;
  /** Fingerprint of the Luau sources the plugin was built from. */
  buildId: string;
  /** "sse" when the plugin holds a live stream, "poll" for the fallback. */
  transport: "sse" | "poll";
}

export interface StudioSession extends StudioIdentity {
  connectedAt: number;
  lastSeenAt: number;
}

/**
 * Bumped whenever `Command`/`CommandResult` shapes change incompatibly. The
 * plugin sends its own value at handshake so we can tell the user to update
 * rather than failing with a confusing schema error later.
 */
export const PROTOCOL_VERSION = 1;

/**
 * Custom header every plugin request must carry. Browsers cannot set it on a
 * cross-origin request without a preflight the bridge never answers, which is
 * what stops a malicious web page from driving the user's Studio via DNS
 * rebinding. Cheaper and less fragile than a token the user has to copy.
 */
export const CLIENT_HEADER = "x-roblox-studio-mcp";
